services:
  hub:
    build:
      context: .
      dockerfile: docker/hub/Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - LANTERN_HUB_HOST=hub
    ports:
      - "8000:8000"
      - "51000-51050:51000-51050/udp"

  device1:
    build:
      context: .
      dockerfile: docker/device/Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - LANTERN_SERVER_URL=http://hub:8000
    depends_on:
      - hub

  device2:
    build:
      context: .
      dockerfile: docker/device/Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - LANTERN_SERVER_URL=http://hub:8000
    depends_on:
      - hub

  device3:
    build:
      context: .
      dockerfile: docker/device/Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - LANTERN_SERVER_URL=http://hub:8000
    depends_on:
      - hub
