from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

LongText = sa.UnicodeText().with_variant(mssql.NVARCHAR(None), "mssql")


revision: str = 'a62e8814af4b'
down_revision: Union[str, Sequence[str], None] = '9a1f6b2c4d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Unicode(255), nullable=False),
    sa.Column('blob', LongText, nullable=False),
    sa.Column('uploaded_by_device_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rental_id', 'filename')
    )
    op.add_column('devices', sa.Column('wg_public_key', sa.Unicode(255), nullable=True))
    op.add_column('devices', sa.Column('wg_ip', sa.Unicode(50), nullable=True))
    op.add_column('devices', sa.Column('has_workspace_key', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('devices', sa.Column('pending_key_offer_blob', LongText, nullable=True))
    op.add_column('devices', sa.Column('pending_key_offer_from', sa.Unicode(255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'pending_key_offer_from')
    op.drop_column('devices', 'pending_key_offer_blob')
    op.drop_column('devices', 'has_workspace_key')
    op.drop_column('devices', 'wg_ip')
    op.drop_column('devices', 'wg_public_key')
    op.drop_table('sync_files')
    # ### end Alembic commands ###
